<a href="https://colab.research.google.com/github/skj092/pytorch101/blob/main/1_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np 

In [2]:
torch.cuda.is_available()

True

In [3]:
!nvidia-smi

Tue Apr 13 11:03:00 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.67       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P8    11W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
a = [[1,2,3],[4,5,6]]

In [5]:
type(a)

list

In [6]:
np.array(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.asarray(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a = torch.tensor(a)

In [10]:
type(a)

torch.Tensor

In [11]:
a.dtype

torch.int64

In [12]:
numpy_array = np.random.rand(3,4)

In [13]:
numpy_array

array([[0.54801379, 0.75550145, 0.94187472, 0.2634096 ],
       [0.37572678, 0.35714063, 0.64408406, 0.28669229],
       [0.88225531, 0.71032891, 0.5720392 , 0.33355991]])

In [14]:
torch.from_numpy(numpy_array)

tensor([[0.5480, 0.7555, 0.9419, 0.2634],
        [0.3757, 0.3571, 0.6441, 0.2867],
        [0.8823, 0.7103, 0.5720, 0.3336]], dtype=torch.float64)

In [15]:
torch.tensor(numpy_array)

tensor([[0.5480, 0.7555, 0.9419, 0.2634],
        [0.3757, 0.3571, 0.6441, 0.2867],
        [0.8823, 0.7103, 0.5720, 0.3336]], dtype=torch.float64)

In [17]:
## Tensor Operations

In [18]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [19]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
my_tensor = torch.rand(3,5)
my_tensor

tensor([[0.1368, 0.7982, 0.6192, 0.4124, 0.6531],
        [0.6386, 0.6071, 0.7023, 0.2097, 0.9566],
        [0.9366, 0.4974, 0.1943, 0.0431, 0.2707]])

In [23]:
my_tensor.dtype

torch.float32

In [24]:
my_tensor.device

device(type='cpu')

In [25]:
my_tensor = my_tensor.to('cuda')

In [27]:
my_tensor.device

device(type='cuda', index=0)

In [28]:
my_tensor[:,1]

tensor([0.7982, 0.6071, 0.4974], device='cuda:0')

In [29]:
my_tensor[:,:2]

tensor([[0.1368, 0.7982],
        [0.6386, 0.6071],
        [0.9366, 0.4974]], device='cuda:0')

In [30]:
my_tensor.mul(my_tensor)

tensor([[0.0187, 0.6371, 0.3834, 0.1700, 0.4266],
        [0.4078, 0.3686, 0.4932, 0.0440, 0.9150],
        [0.8772, 0.2474, 0.0378, 0.0019, 0.0733]], device='cuda:0')

In [31]:
my_tensor*my_tensor

tensor([[0.0187, 0.6371, 0.3834, 0.1700, 0.4266],
        [0.4078, 0.3686, 0.4932, 0.0440, 0.9150],
        [0.8772, 0.2474, 0.0378, 0.0019, 0.0733]], device='cuda:0')

In [32]:
my_tensor.matmul(my_tensor.T)

tensor([[1.6358, 1.7180, 0.8400],
        [1.7180, 2.2285, 1.3045],
        [0.8400, 1.3045, 1.2375]], device='cuda:0')

In [33]:
torch.matmul(my_tensor, my_tensor.T)

tensor([[1.6358, 1.7180, 0.8400],
        [1.7180, 2.2285, 1.3045],
        [0.8400, 1.3045, 1.2375]], device='cuda:0')

In [34]:
my_tensor @ my_tensor.T

tensor([[1.6358, 1.7180, 0.8400],
        [1.7180, 2.2285, 1.3045],
        [0.8400, 1.3045, 1.2375]], device='cuda:0')

In [35]:
my_tensor.sum()

tensor(7.6760, device='cuda:0')

In [36]:
my_tensor.sum(axis=0)

tensor([1.7120, 1.9026, 1.5158, 0.6652, 1.8804], device='cuda:0')

In [37]:
# torch.max, torch.min

In [39]:
torch.cat([my_tensor, my_tensor])

tensor([[0.1368, 0.7982, 0.6192, 0.4124, 0.6531],
        [0.6386, 0.6071, 0.7023, 0.2097, 0.9566],
        [0.9366, 0.4974, 0.1943, 0.0431, 0.2707],
        [0.1368, 0.7982, 0.6192, 0.4124, 0.6531],
        [0.6386, 0.6071, 0.7023, 0.2097, 0.9566],
        [0.9366, 0.4974, 0.1943, 0.0431, 0.2707]], device='cuda:0')

In [41]:
torch.cat([my_tensor, my_tensor], axis=0)

tensor([[0.1368, 0.7982, 0.6192, 0.4124, 0.6531],
        [0.6386, 0.6071, 0.7023, 0.2097, 0.9566],
        [0.9366, 0.4974, 0.1943, 0.0431, 0.2707],
        [0.1368, 0.7982, 0.6192, 0.4124, 0.6531],
        [0.6386, 0.6071, 0.7023, 0.2097, 0.9566],
        [0.9366, 0.4974, 0.1943, 0.0431, 0.2707]], device='cuda:0')

In [43]:
torch.nn.functional.softmax(my_tensor, dim=1)

tensor([[0.1324, 0.2566, 0.2145, 0.1745, 0.2220],
        [0.1976, 0.1915, 0.2106, 0.1287, 0.2716],
        [0.3286, 0.2118, 0.1564, 0.1345, 0.1688]], device='cuda:0')

In [44]:
my_tensor.shape

torch.Size([3, 5])

In [46]:
my_tensor.size()

torch.Size([3, 5])

In [47]:
my_tensor.size(0)

3

In [49]:
torch.rand(10,3,128,128).size

<function Tensor.size>

In [50]:
my_tensor

tensor([[0.1368, 0.7982, 0.6192, 0.4124, 0.6531],
        [0.6386, 0.6071, 0.7023, 0.2097, 0.9566],
        [0.9366, 0.4974, 0.1943, 0.0431, 0.2707]], device='cuda:0')

In [52]:
my_tensor.clip(0.2,0.8)

tensor([[0.2000, 0.7982, 0.6192, 0.4124, 0.6531],
        [0.6386, 0.6071, 0.7023, 0.2097, 0.8000],
        [0.8000, 0.4974, 0.2000, 0.2000, 0.2707]], device='cuda:0')

In [53]:
my_tensor.cpu().detach().numpy()

array([[0.13684201, 0.7981615 , 0.6191973 , 0.4123652 , 0.6531337 ],
       [0.6386037 , 0.60710645, 0.7022597 , 0.20966041, 0.95656353],
       [0.93659204, 0.49737662, 0.19431561, 0.04313368, 0.2706704 ]],
      dtype=float32)