<a href="https://colab.research.google.com/github/skj092/pytorch101/blob/main/2_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import torch

In [55]:
a = torch.tensor([5.], requires_grad=True)
b = torch.tensor([3.], requires_grad=True)

In [56]:
y = a**3 + b**2
y

tensor([134.], grad_fn=<AddBackward0>)

In [57]:
# dy/da = 3*a**2=3*5**2=75
# dy/db = 2*b = 2*3 = 6

In [58]:
print(a.grad)
print(b.grad)

None
None


In [59]:
y.backward()

In [61]:
a.grad

tensor([75.])

In [62]:
b.grad

tensor([6.])

In [63]:
w = torch.randn(5,1, requires_grad=True)
b = torch.rand(1, requires_grad=True)

In [64]:
w

tensor([[ 0.1652],
        [-1.8434],
        [-1.0312],
        [-0.3729],
        [ 0.3186]], requires_grad=True)

In [65]:
x = torch.rand(1,5)

In [66]:
x

tensor([[0.5354, 0.7935, 0.9856, 0.0547, 0.6498]])

In [67]:
output = torch.matmul(x,w)+b

In [68]:
loss = 1-output

In [69]:
loss

tensor([[3.0251]], grad_fn=<RsubBackward1>)

In [70]:
output

tensor([[-2.0251]], grad_fn=<AddBackward0>)

In [71]:
loss.backward()

In [72]:
w.grad

tensor([[-0.5354],
        [-0.7935],
        [-0.9856],
        [-0.0547],
        [-0.6498]])

In [73]:
b.grad

tensor([-1.])

In [74]:
with torch.no_grad():
  w = w-0.01*w.grad.data

In [75]:
w

tensor([[ 0.1706],
        [-1.8354],
        [-1.0214],
        [-0.3723],
        [ 0.3251]])